Analyse de l'effet de 3 symétries différentes sur les atomes de notre cristal.

# Modules et packages

In [6]:
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.operations import SymmOp
from jupyter_jsmol.pymatgen import quick_view
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [7]:

with MPRester ("n58KMF7umZMAJXouXDJc0vORWlcEfEsD") as m:
    structure = m.get_structure_by_material_id("mp-15794")

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:


struct = SpacegroupAnalyzer(structure,symprec=0.1)
conv_struc = struct.get_conventional_standard_structure()
symmops = struct.get_space_group_operations()


In [9]:
# Sélection de trois opérations de symétrie différentes (hors identité)
symm_ops_selected = symmops[1:4]  # On prend trois premières après l'identité

# Appliquer chaque opération sur un atome différent
atoms = conv_struc.sites[:3]  # Prendre trois atomes différents
transformed_atoms = [op.operate(atom.coords) for op, atom in zip(symm_ops_selected, atoms)]

In [10]:
# Affichage des opérations de symétrie et visualisation après chaque transformation
print(f"Groupe d'espace: {struct.get_space_group_symbol()}")
for i, (op, atom, transformed) in enumerate(zip(symm_ops_selected, atoms, transformed_atoms)):
    print(f"Opération {i+1}: {op}")
    print(f"Atome original: {atom}")
    print(f"Atome transformé: {transformed}\n")
    
    # Création d'une structure temporaire pour visualisation
    temp_structure = conv_struc.copy()
    temp_structure.append("X", transformed, coords_are_cartesian=True)
    try:
        view_transformed = quick_view(temp_structure)
        display(view_transformed)
    except ValueError as e:
        print(f"Erreur lors de la visualisation: {e}")
    print(f"Visualisation de la structure après l'opération {i+1}")

Groupe d'espace: R-3m
Opération 1: Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.]
Atome original: [2.02965769 1.17182341 3.22695525] Li
Atome transformé: [2.02965769 1.17182341 3.22695525]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Visualisation de la structure après l'opération 1
Opération 2: Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Atome original: [ 4.05931538e+00 -4.44089210e-16  9.68086575e+00] Li
Atome transformé: [-4.05931538e+00  4.44089210e-16 -9.68086575e+00]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Visualisation de la structure après l'opération 2
Opération 3: Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Atome original: [ 2.02965769 -1.17182341 16.13477624] Li
Atome transformé: [ -2.02965769   1.17182341 -16.13477624]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Visualisation de la structure après l'opération 3


Opération 1 : Il s’agit d’une rotation identité (matrice unité), ce qui signifie que la structure ne subit aucune transformation.

Opération 2 : Une rotation d’ordre -1 qui inverse les coordonnées de l’atome étudié, indiquant une symétrie par inversion centrale.

Opération 3 : Même type de rotation qu’en opération 2, mais appliquée à un autre atome, montrant un comportement symétrique cohérent dans la structure.